### ISSUE TITLE
lost inheritance

### ISSUE THREAD

**Issue by janseng1970** [teq/serialazy#11]
Hello,

I have a class model, where i was able to put mutch of the properties in the base class an only in part of the cases a have to add properties but make descisions on the type. But serialazy lost the type if there are no properties in the chain or none of the properties are serialized. Example:

Code:
====
class Person {
   @Serialize({ optional: true })   public Name?:  string;
   @Serialize({ optional: true })   public Surname?: string;
}

class Employer extends Person {
                                    public Unit?:  string;
}

const employer = new Employer();
employer.Name = "Dug";
employer.Surname ="Donald";
employer.Unit = "Finance";          
console.log(employer);

const deflatedEmployer = deflate(employer);
console.log(deflatedEmployer);

const inflatedEmployer = inflate<Employer>(Employer, deflatedEmployer);
console.log(inflatedEmployer);

Output:
===== 
Employer {Name: "Dug", Surname: "Donald", Unit: "Finance"}
AppSession.ts:76
[[StableObjectId]]:5
Name:"Dug"
Surname:"Donald"
Unit:"Finance"
__proto__:Person {constructor: }

Object {Name: "Dug", Surname: "Donald"}
AppSession.ts:79
[[StableObjectId]]:9
Name:"Dug"
Surname:"Donald"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}

Person {Name: "Dug", Surname: "Donald"}
AppSession.ts:82
[[StableObjectId]]:12
Name:"Dug"
Surname:"Donald"
__proto__:Object {constructor: }

I would expect, that inflate returns "Employer" as class with undefiend for the propertie "Unit", but the function returns "Person". If "Employer" yust extends "Person" with no properties lead to steh same result.

**Comment by teq** [comment]
@janseng1970 It is obviously a bug, thank you for pointing out. I will investigate.

**Comment by teq** [comment]
Fixed in [v2.0.2](https://www.npmjs.com/package/serialazy/v/2.0.2)
