### ISSUE TITLE
Recursive serialization with optional properties

### ISSUE THREAD

**Issue by janseng1970** [teq/serialazy#6]
Hello,

this modified example will not work:

class Author {
    @Serialize({ optional: true}) public name?: string;
}

class Book {
    @Serialize() public title: string;
    @Serialize({ optional: true}) public author?: Author; // Serializes Author recursively
}

You will get an error like "Cannot read property 'name' of undefined" in case there is no 'author'. There is no difference if you make the 'name' property optional or not. So the up function of the serializer can't handle optional in deep. Propably the down has the same problem.

**Comment by teq** [comment]
@janseng1970 Thank you for reporting this issue. Fixed in [v2.0.1](https://www.npmjs.com/package/serialazy/v/2.0.1)
